name: happy_pleace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  html: ^0.15.5
  http: ^1.2.2
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path: 'assets/images/appicon/happy_place_icon.png'


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/appicon/happy_place_icon.png
    - assets/locations/
    - assets/profilimage/
